[package]
name = "rujs"
version = "0.1.0"
edition = "2021"
license = "ISC OR MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc="0.2.126"

[build-dependencies]
cc = "1.0.73"
bindgen = "0.60.1"
